# Generated by Django 6.0.2 on 2026-02-08 14:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGenrePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, unique=True)),
                ('genre_scores', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('interaction_type', models.CharField(choices=[('view', 'Product View'), ('search', 'Search Query'), ('cart_add', 'Added to Cart'), ('wishlist_add', 'Added to Wishlist'), ('purchase', 'Purchase')], max_length=20)),
                ('search_query', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.product')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'interaction_type'], name='books_userb_user_b68cc1_idx'), models.Index(fields=['product', 'interaction_type'], name='books_userb_product_c09a39_idx'), models.Index(fields=['timestamp'], name='books_userb_timesta_e49969_idx')],
            },
        ),
    ]
