# Generated by Django 6.0.2 on 2026-03-21 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_product_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='listing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('archived', 'Archived')], default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sell'), ('swap', 'Swap'), ('donate', 'Donate')], default='sell', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='swap_preference',
            field=models.CharField(blank=True, help_text='Title or genre of the book you want in exchange.', max_length=255, null=True),
        ),
    ]
