# Generated by Django 6.0.2 on 2026-03-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_product_listing_status_product_listing_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, help_text='Physical condition of the book for swapping (e.g. New, Like New, Good, Heavily Used).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Email for other users to contact you for swapping', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(blank=True, help_text='City or neighborhood for the swap', max_length=255, null=True),
        ),
    ]
