# Generated by Django 6.0.2 on 2026-03-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_product_condition_product_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='listing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='approved', max_length=20),
        ),
    ]
