# Generated by assistant to replace zip_code with email
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0008_product_average_rating_product_rating_count_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingaddress",
            name="email",
            field=models.EmailField(default="", max_length=254),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="shippingaddress",
            name="zip_code",
        ),
    ]
