# Generated by Django 6.0.2 on 2026-04-06 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingBook',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Book Approval',
                'verbose_name_plural': '⏳ Pending Book Approvals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('books.product',),
        ),
    ]
