# Generated by Django 6.0.2 on 2026-04-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_order_status_rename'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_order_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
