# Generated by Django 6.0.2 on 2026-04-11 04:48
# Data migration: assigns per-user sequential order numbers to all
# existing completed orders, sorted by date_ordered ascending.

from django.db import migrations


def backfill_user_order_numbers(apps, schema_editor):
    Order = apps.get_model('books', 'Order')

    # Collect distinct users who have at least one completed order
    usernames = (
        Order.objects
        .filter(complete=True)
        .values_list('user', flat=True)
        .distinct()
    )

    for username in usernames:
        user_orders = (
            Order.objects
            .filter(user=username, complete=True)
            .order_by('date_ordered')   # chronological → #1 is their first ever order
        )
        for i, order in enumerate(user_orders, start=1):
            order.user_order_number = i
            order.save(update_fields=['user_order_number'])


def reverse_backfill(apps, schema_editor):
    Order = apps.get_model('books', 'Order')
    Order.objects.filter(complete=True).update(user_order_number=None)


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_add_user_order_number'),
    ]

    operations = [
        migrations.RunPython(backfill_user_order_numbers, reverse_backfill),
    ]
