# Generated by Django 6.0.2 on 2026-02-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_preregistration_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='preregistration',
            name='email',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='preregistration',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='preregistration',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='preregistration',
            name='password1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='preregistration',
            name='password2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='preregistration',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
