# Generated by Django 6.0.2 on 2026-03-19 13:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_usergenrepreference_userbehavior'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'View'), ('wishlist', 'Wishlist'), ('cart', 'Cart'), ('purchase', 'Purchase')], max_length=20)),
                ('weight', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interactions', to='books.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'book', 'action')},
            },
        ),
    ]
